cats99/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, only: [:index, :show, :new, :create]
end

cats99/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

cats99/app/models/cat.rb
# == Schema Information
#
# Table name: cats
#
#  id          :bigint           not null, primary key
#  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)
#  description :text             not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#
class Cat < ApplicationRecord
    require 'date'
    COLORS_OF_CATS = %w(Black Brown Orange Green Gray).freeze
    include ActionView::Helpers::DateHelper
    
    validates :color, inclusion: COLORS_OF_CATS
    validates :sex, inclusion: %w(M F)
    validates :name, :sex, :birth_date, :color, presence: true
 
    def age
        # now = Date.today
        # b_day = Date.parse(:birth_date.to_s)
        # age = now.year - b_day.year
        # age
        time_ago_in_words(birth_date)
    end
end

cats99/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

cats99/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    def index
        @cats = Cat.all
        render :index
    end

    def show
        @cat = Cat.find(params[:id])
        render :show
    end

    def new
        @cat = Cat.new
        render :new
    end

    def create
        @cat = Cat.new(cat_params)
        if @cat.save
            render json: @cat
        else
            render json: @cat.errors.full_messages, status: :unprocessable_entity
        end
    end


    private
    def cat_params
        params.require(:cat).permit(:birth_date, :name, :color, :sex, :description)
    end
end

cats99/app/helpers/application_helper.rb
module ApplicationHelper
end

cats99/app/views/cats/index.html.erb
<h1>ALL CATS!</h1>

<ul>
    <% @cats.each do |cat| %>
        <li>
            <%= cat.name%> 
        </li>
        <a href="<%= cat_url(cat) %>">Show Page</a>
    <% end %>
</ul> 

cats99/app/views/cats/new.html.erb
<h1>Create A Cat</h1>

<form action="<%= cats_url %>" method="POST">
<label>Name:
    <input 
        type="text"
        name="cat[name]"
        value="<%= @cat.name %>">
</label>
<br>
<br>
<label>Color: 
<select name="cat[color]">
    <option disabled selected>-- Please Select --</option>
    <option value="Black">Black</option>
    <option value="Brown">Brown</option>
    <option value="Orange">Orange</option>
    <option value="Green">Green</option>
    <option value="Gray">Gray</option>
</select>
<br>
<br>
<label>Birth date:
    <input type="date"  name= "cat[birth_date]" value="<%= @cat.birth_date %>">
</label>
<br>
<br>
<label> Sex:
<select name="cat[sex]">
    <option disabled selected>-- Please Select --</option>
    <option value="F">Female</option>
    <option value="M">Male</option>
</select>
</label>
<br>
<br>
<label>Description:
  
    <textarea name="cat[description]"
        value="<%= @cat.description %>"></textarea>
</label>
<br>
<br>
<input type="submit" value="Create Cat">

</form>

cats99/app/views/cats/show.html.erb
<h1>A Single Great Cat</h1>

<table>
    <tr>
        <th>Attribute</th>
        <th>Value</th>
    </tr>
    <tr>
        <td>Name</td>
        <td><%=@cat.name%></td>
    </tr>
    <tr>
        <td>Color</td>
        <td><%=@cat.color%></td>
    </tr>
    <tr>
        <td>Birthdate</td>
        <td><%=@cat.birth_date%></td>
    </tr>
    <tr> 
        <td>Age</td>
        <td><%=@cat.age%></td>
    </tr>
    <tr>
        <td>Sex</td>
        <td><%=@cat.sex%></td>
    </tr>
    <tr>
        <td>Description</td>
        <td><%=@cat.description%></td>
    </tr>
</table>

<!-- <li>
    <%= @cat.name %>, <%= @cat.color %>, <%= @cat.sex %>
</li>
<li>
    <%= @cat.description %>
</li> -->

<!-- #  birth_date  :date             not null
#  color       :string           not null
#  name        :string           not null
#  sex         :string(1)
#  description :text             not null -->

cats99/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cats99</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>